version: "3"
services:
  server:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports: 
      - "8080:80"
    expose:
      - "80"
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./log/nginx:/var/log/nginx/
  php:
    image: php:8.2-fpm-alpine
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./log/php.log:/var/log/fpm-php.www.log
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    networks:
      - internal
    volumes:
      - ./:/home/
  speed-tests:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    networks:
      - internal
    volumes:
      - ./:/home/
networks:
  internal:
    driver: bridge
