version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./log/nginx:/var/log/nginx/
  php:
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./log/php.log:/var/log/fpm-php.www.log
networks:
  internal:
    driver: bridge
